### ISSUE TITLE
Questions about dataloader

### ISSUE THREAD

**Issue by zp19990818** [zwbx/DFM-Net#11]
Hi， Your work is really inspiring!

However， When I was training, the following errors occurred：

Traceback (most recent call last):
  File "E:/IEdownloads/git_project/small_paper2/DFM-Net-Extension/train.py", line 143, in <module>
    train_loader = get_loader(image_root, gt_root, depth_root, batchsize=opt.batchsize, trainsize=opt.trainsize)
  File "E:\IEdownloads\git_project\small_paper2\DFM-Net-Extension\data.py", line 202, in get_loader
    dataset = SalObjDataset(image_root, gt_root, depth_root, trainsize)
TypeError: __init__() missing 1 required positional argument: 'trainsize'

![image](https://github.com/zwbx/DFM-Net/assets/53686038/fbcb17d5-9f0b-4487-b230-b6d4e03891a1)

I tried Debug and the output shows that trainsize is obtainable. Now I don't know what's wrong, can you help me?

**Comment by zwbx** [comment]
Please check your setting.
