### ISSUE TITLE
HI，GREAT WORK!

### ISSUE THREAD

**Issue by gayuyu** [zwbx/DFM-Net#12]
HI，GREAT WORK!

i have serval questions, is there a edge dataset exit in your data?
or how can i got this edge data?

**Comment by zwbx** [comment]
no, it is not required. you just need to remove it.
________________________________
发件人: gayuyu ***@***.***>
发送时间: 2023年7月14日 18:08
收件人: zwbx/DFM-Net ***@***.***>
抄送: Subscribed ***@***.***>
主题: [zwbx/DFM-Net] HI，GREAT WORK! (Issue #12)


CAUTION: External email. Only click on links or open attachments from trusted senders.

________________________________
HI，GREAT WORK!

i have serval questions, is there a edge dataset exit in your data?
or how can i got this edge data?
