### ISSUE TITLE
architecture of DHA

### ISSUE THREAD

**Issue by clelouch** [zwbx/DFM-Net#4]
it seems that the figure.4 (architecture of DHA) is not consistent with the code.
![image](https://user-images.githubusercontent.com/33519394/133731363-34bd8a49-0410-400c-bd8c-495e2ef2506d.png)
![image](https://user-images.githubusercontent.com/33519394/133731418-c3362ea4-14a8-4eea-a511-121ca622a987.png)

**Comment by zwbx** [comment]
Thanks for your comment!
It's a mistake that these residual connections are repeatedly added.
However the influence is limited according to our experience, and we'll fix it in the next version.
