### ISSUE TITLE
系数计算问题

### ISSUE THREAD

**Issue by infinite013** [zwbx/DFM-Net#6]
您的论文中包含了一些对应元素相乘的操作
如在DQW中
![image](https://user-images.githubusercontent.com/37789662/141416496-daaffe7a-ea13-4048-841c-31c75ed9c59f.png)
在DHA中
![image](https://user-images.githubusercontent.com/37789662/141416544-184fc6c0-248e-4875-be82-5e429e31525b.png)
我不是很能理解这种乘法的意义，也即，这种乘法能为我们带来什么信息
您能说一下嘛

**Comment by zwbx** [comment]
V_BA这个公式是对feature进行了类似求Dice系数的操作。

pixel-wise乘法的意义：首先feature经过ReLU激活函数，其值是大于等于0的。此时feature相乘可以近似看做对其求交集（实验发现大部分情况激活值小于1，可忽略大于1的情况）。DHA使用乘法获得两个模态的公共特征，考虑到深度图有噪音，公共特征的可信度是更高的，我们用公共特征来优化f_d^5不准确的定位。

之前的文章也使用了像素乘法。可参见下文的Point-to-Point style部分。
https://openaccess.thecvf.com/content_ICCV_2019/papers/Wu_Stacked_Cross_Refinement_Network_for_Edge-Aware_Salient_Object_Detection_ICCV_2019_paper.pdf

**Comment by infinite013** [comment]
非常感谢，顺便问一下：
DHA的结构是您经过试验确定的结构还是受到其他工作的启发设定的结构
我想试试这个思路能否在我的工作中work

**Comment by zwbx** [comment]
这结构是本文的创新点。可以说是一种改进的空间注意力。
使用一个feature对另一个feature加权以起到过滤作用的思想出现过在：
CPD: Cascaded Partial Decoder for Accurate and Fast Salient Object Detection
BBS-Net: RGB-D Salient Object Detection with a Bifurcated Backbone Strategy Network

但DHA的不同点在于：
1.设计考虑到高效性，迭代使用下采样和空洞卷积快速增大感受野，且一次计算输出多个注意力。
2.结合了RGB的底层特征对注意力进行优化。

**Comment by zwbx** [comment]
欢迎在你的工作中使用DQW和DHA进行高效提点，期待你的反馈:- )
